; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                  = 7160725-64-bit MS Windows           
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppAnalyzeUserTree                    = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Analyze a User Tree                 
Tree to Use                          = Use tree from file                  
Keep user tree branch lengths        = Yes                                 
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = Hasegawa-Kishino-Yano model         
Rates and Patterns                   = ====================                
Rates among Sites                    = Gamma Distributed (G)               
No of Discrete Gamma Categories      = 4                                   
Assume Molecular Clock               = No                                  
Clock Stringency Type                = Not Applicable                      
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Use all sites                       
Site Coverage Cutoff (%)             = Not Applicable                      
System Resource Usage                = ====================                
Number of Threads                    = 1                                   
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
