; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 10180629-x86_64 MS Windows          
[ DataSettings ]
datatype                             = snProtein                           
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppAnalyzeUserTree                    = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Analyze a User Tree                 
Tree to Use                          = Use tree from file                  
Reltime Settings                     = ====================                
Max Relative Rate Ratio              = 20                                  
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Amino acid                          
Model/Method                         = Poisson model                       
Rates and Patterns                   = ====================                
Rates among Sites                    = Uniform Rates                       
No of Discrete Gamma Categories      = Not Applicable                                    
Assume Molecular Clock               = No                                  
Clock Stringency Type                = Not Applicable                      
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Use all sites                       
Site Coverage Cutoff (%)             = Not Applicable                      
System Resource Usage                = ====================                
Number of Threads                    = 1                                   
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
